name: ci

on:
  push:
    branches: master

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build docker
        run: docker build -t ghcr.io/xaqq/my-test-image .
      - name: Push docker
        run: docker push ghcr.io/xaqq/my-test-image
